#!/bin/bash

echo "=== macOS設定値確認 ==="
echo ""
echo "■ 基本設定"
echo "Bluetooth表示設定: $(defaults read com.apple.controlcenter "NSStatusItem Visible Bluetooth" 2>/dev/null || echo '未設定')"
echo "Dock自動非表示: $(defaults read com.apple.dock autohide 2>/dev/null || echo '未設定')"
echo ""
echo "■ Finder設定"
echo "Finderパス表示: $(defaults read com.apple.finder _FXShowPosixPathInTitle 2>/dev/null || echo '未設定')"
echo "隠しファイル表示: $(defaults read com.apple.finder AppleShowAllFiles 2>/dev/null || echo '未設定')"
echo "パスバー表示: $(defaults read com.apple.finder ShowPathbar 2>/dev/null || echo '未設定')"
echo ""
echo "■ キーボード・マウス設定"
echo "キーボード初期遅延: $(defaults read -g InitialKeyRepeat 2>/dev/null || echo '未設定')"
echo "キーリピート速度: $(defaults read -g KeyRepeat 2>/dev/null || echo '未設定')"
echo "トラックパッド速度: $(defaults read -g com.apple.trackpad.scaling 2>/dev/null || echo '未設定')"
echo "タップでクリック: $(defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking 2>/dev/null || echo '未設定')"
echo "スクロール方向: $(defaults read NSGlobalDomain com.apple.swipescrolldirection 2>/dev/null || echo '未設定')"
echo ""
echo "■ スクリーンショット設定"
echo "保存先: $(defaults read com.apple.screencapture location 2>/dev/null || echo '未設定')"
echo "影設定: $(defaults read com.apple.screencapture disable-shadow 2>/dev/null || echo '未設定')"
echo "形式: $(defaults read com.apple.screencapture type 2>/dev/null || echo '未設定')"
echo ""
echo "■ Dock設定"
echo "サイズ: $(defaults read com.apple.dock tilesize 2>/dev/null || echo '未設定')"
echo "拡大機能: $(defaults read com.apple.dock magnification 2>/dev/null || echo '未設定')"
echo "拡大サイズ: $(defaults read com.apple.dock largesize 2>/dev/null || echo '未設定')"
echo "Dock位置: $(defaults read com.apple.dock orientation 2>/dev/null || echo '未設定')"
echo ""
echo "■ システム設定"
echo "拡張子表示: $(defaults read -g AppleShowAllExtensions 2>/dev/null || echo '未設定')"
echo "起動音設定: $(nvram StartupMute 2>/dev/null || echo '取得できません（sudo権限が必要）')"
echo ""
echo "=== 確認完了 ==="
